# Generated by Django 4.2.1 on 2023-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='local',
        ),
        migrations.AddField(
            model_name='organization',
            name='file',
            field=models.ImageField(blank=True, db_column='File', default=None, upload_to=''),
        ),
    ]
