# Generated by Django 4.2.1 on 2023-12-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationrating',
            old_name='grade',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='organizationrating',
            name='is_anonymous',
            field=models.BooleanField(db_column='IsAnonymous', default=False),
        ),
        migrations.AddField(
            model_name='organizationrating',
            name='is_approved',
            field=models.BooleanField(db_column='IsApproved', default=False),
        ),
        migrations.AddField(
            model_name='organizationrating',
            name='name',
            field=models.CharField(db_column='Name', default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationrating',
            name='remarks',
            field=models.TextField(db_column='Remarks', default=None, null=True),
        ),
    ]
