# Generated by Django 4.2.1 on 2023-12-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_rename_grade_organizationrating_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrating',
            name='email',
            field=models.CharField(db_column='Email', default=None, max_length=255, null=True),
        ),
    ]
