# Generated by Django 4.2.1 on 2023-12-04 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organizationrating_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrating',
            name='organization',
            field=models.ForeignKey(db_column='EventId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_rating', to='organization.organization'),
        ),
    ]
